-- Escritura improvisada
vim.keymap.set("i", "cx", "ĉ", { noremap = true, silent = true })
vim.keymap.set("i", "gx", "ĝ", { noremap = true, silent = true })
vim.keymap.set("i", "hx", "ĥ", { noremap = true, silent = true })
vim.keymap.set("i", "jx", "ĵ", { noremap = true, silent = true })
vim.keymap.set("i", "sx", "ŝ", { noremap = true, silent = true })
vim.keymap.set("i", "ux", "ŭ", { noremap = true, silent = true })

-- Letras con Sombrero y Macrón Inferior (Versión Larga) - Mayúsculas
vim.keymap.set("i", "Cx", "Ĉ", { noremap = true, silent = true })
vim.keymap.set("i", "Gx", "Ĝ", { noremap = true, silent = true })
vim.keymap.set("i", "Hx", "Ĥ", { noremap = true, silent = true })
vim.keymap.set("i", "Jx", "Ĵ", { noremap = true, silent = true })
vim.keymap.set("i", "Sx", "Ŝ", { noremap = true, silent = true })

-- La E breve
vim.api.nvim_set_keymap("i", "<C-e>", "ĕ", { noremap = true, silent = true })
-- Vocales Áureas (Escribes .a y se convierte en ā)
vim.keymap.set("i", ";a", "ā", { noremap = true, silent = true })
vim.keymap.set("i", ";A", "Ā", { noremap = true, silent = true })
vim.keymap.set("i", ";e", "ē", { noremap = true, silent = true })
vim.keymap.set("i", ";E", "Ē", { noremap = true, silent = true })
vim.keymap.set("i", ";i", "ī", { noremap = true, silent = true })
vim.keymap.set("i", ";I", "Ī", { noremap = true, silent = true })
vim.keymap.set("i", ";o", "ō", { noremap = true, silent = true })
vim.keymap.set("i", ";O", "Ō", { noremap = true, silent = true })
vim.keymap.set("i", ";u", "ū", { noremap = true, silent = true })
vim.keymap.set("i", ";U", "Ū", { noremap = true, silent = true })

-- Consonantes Áureas (Letra + Macron) - Minúsculas
vim.keymap.set("i", ";b", "b̄", { noremap = true, silent = true })
vim.keymap.set("i", ";c", "c̄", { noremap = true, silent = true })
vim.keymap.set("i", ";d", "d̄", { noremap = true, silent = true })
vim.keymap.set("i", ";f", "f̄", { noremap = true, silent = true })
vim.keymap.set("i", ";g", "ḡ", { noremap = true, silent = true })
vim.keymap.set("i", ";h", "h̄", { noremap = true, silent = true })
vim.keymap.set("i", ";j", "j̄", { noremap = true, silent = true })
vim.keymap.set("i", ";k", "k̄", { noremap = true, silent = true })
vim.keymap.set("i", ";l", "l̄", { noremap = true, silent = true })
vim.keymap.set("i", ";m", "m̄", { noremap = true, silent = true })
vim.keymap.set("i", ";n", "n̄", { noremap = true, silent = true })
vim.keymap.set("i", ";p", "p̄", { noremap = true, silent = true })
vim.keymap.set("i", ";r", "r̄", { noremap = true, silent = true })
vim.keymap.set("i", ";s", "s̄", { noremap = true, silent = true })
vim.keymap.set("i", ";t", "t̄", { noremap = true, silent = true })
vim.keymap.set("i", ";v", "v̄", { noremap = true, silent = true })
vim.keymap.set("i", ";z", "z̄", { noremap = true, silent = true })

-- Consonantes Áureas (Letra + Macron) - Mayúsculas
vim.keymap.set("i", ";B", "B̄", { noremap = true, silent = true })
vim.keymap.set("i", ";C", "C̄", { noremap = true, silent = true })
vim.keymap.set("i", ";D", "D̄", { noremap = true, silent = true })
vim.keymap.set("i", ";F", "F̄", { noremap = true, silent = true })
vim.keymap.set("i", ";G", "Ḡ", { noremap = true, silent = true })
vim.keymap.set("i", ";H", "H̄", { noremap = true, silent = true })
vim.keymap.set("i", ";J", "J̄", { noremap = true, silent = true })
vim.keymap.set("i", ";K", "K̄", { noremap = true, silent = true })
vim.keymap.set("i", ";L", "L̄", { noremap = true, silent = true })
vim.keymap.set("i", ";M", "M̄", { noremap = true, silent = true })
vim.keymap.set("i", ";N", "N̄", { noremap = true, silent = true })
vim.keymap.set("i", ";P", "P̄", { noremap = true, silent = true })
vim.keymap.set("i", ";R", "R̄", { noremap = true, silent = true })
vim.keymap.set("i", ";S", "S̄", { noremap = true, silent = true })
vim.keymap.set("i", ";T", "T̄", { noremap = true, silent = true })
vim.keymap.set("i", ";V", "V̄", { noremap = true, silent = true })
vim.keymap.set("i", ";Z", "Z̄", { noremap = true, silent = true })

-- Letras con Sombrero y Macrón Inferior (Versión Larga) - Minúsculas
vim.keymap.set("i", ";ĉ", "ĉ̱", { noremap = true, silent = true })
vim.keymap.set("i", ";ĝ", "ĝ̱", { noremap = true, silent = true })
vim.keymap.set("i", ";ĥ", "ẖ̂", { noremap = true, silent = true })
vim.keymap.set("i", ";ĵ", "ĵ̱", { noremap = true, silent = true })
vim.keymap.set("i", ";ŝ", "ŝ̱", { noremap = true, silent = true })
vim.keymap.set("i", ";ŭ", "ŭ̱", { noremap = true, silent = true })

-- Letras con Sombrero y Macrón Inferior (Versión Larga) - Mayúsculas
vim.keymap.set("i", ";Ĉ", "Ĉ̱", { noremap = true, silent = true })
vim.keymap.set("i", ";Ĝ", "Ĝ̱", { noremap = true, silent = true })
vim.keymap.set("i", ";Ĥ", "Ĥ̱", { noremap = true, silent = true })
vim.keymap.set("i", ";Ĵ", "Ĵ̱", { noremap = true, silent = true })
vim.keymap.set("i", ";Ŝ", "Ŝ̱", { noremap = true, silent = true })
vim.keymap.set("i", ";Ŭ", "Ŭ̱", { noremap = true, silent = true })
